source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OrangeFramework_Specs', :exclusive => true do
  pod "OrangeFramework", :path => "../"
  
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
